module.exports = {
  apps: [
    {
      name:    'machcore-api',
      script:  'dist/src/main.js',
      cwd:     '/home/karkyon/projects/machcore/apps/api',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch:   false,
      max_memory_restart: '512M',
      env: { NODE_ENV: 'production', API_PORT: 3011 },
      error_file: '/home/karkyon/.pm2/logs/machcore-api-error.log',
      out_file:   '/home/karkyon/.pm2/logs/machcore-api-out.log',
    },
    {
      name:        'machcore-web',
      script:      '/home/karkyon/projects/machcore/start-web.sh',
      interpreter: '/bin/bash',
      exec_mode:   'fork',
      instances:   1,
      autorestart: true,
      watch:       false,
      max_memory_restart: '512M',
      env: { NODE_ENV: 'production', PORT: 3010 },
      error_file: '/home/karkyon/.pm2/logs/machcore-web-error.log',
      out_file:   '/home/karkyon/.pm2/logs/machcore-web-out.log',
    },
  ],
};
